databases:
  - name: whisper
    databaseName: whisper_m7rg
    user: whisper_m7rg_user

services:
  - type: web
    name: wspr
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: whisper
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false